# Generated by Django 2.2.1 on 2019-06-08 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BrightWay', '0003_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
