# Generated by Django 2.2.1 on 2019-06-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrightWay', '0004_auto_20190608_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parentuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.TextField()),
                ('UserID', models.TextField()),
                ('UserPW', models.TextField()),
                ('UserFlag', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='Childuser',
        ),
    ]
