# Generated by Django 2.2.2 on 2019-06-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrightWay', '0005_auto_20190608_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentuser',
            name='UserChild1ID',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='parentuser',
            name='UserChild1Name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='parentuser',
            name='UserChild2ID',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='parentuser',
            name='UserChild2Name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='parentuser',
            name='UserChild3ID',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='parentuser',
            name='UserChild3Name',
            field=models.TextField(null=True),
        ),
    ]
