# Generated by Django 2.2.2 on 2019-06-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrightWay', '0006_auto_20190608_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('distinct', models.TextField(null=True)),
                ('time', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cs',
            name='distinct',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='childuser',
            name='UserFlag',
            field=models.TextField(null=True),
        ),
    ]
