# Generated by Django 2.2.2 on 2019-06-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrightWay', '0007_auto_20190610_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Os',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('distinct', models.TextField(null=True)),
            ],
        ),
    ]
