# Generated by Django 2.2.2 on 2019-06-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrightWay', '0008_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fs',
            name='time',
            field=models.TextField(null=True),
        ),
    ]
