# Generated by Django 2.2.2 on 2019-06-11 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BrightWay', '0010_dong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentuser',
            name='UserChild2ID',
        ),
        migrations.RemoveField(
            model_name='parentuser',
            name='UserChild2Name',
        ),
        migrations.RemoveField(
            model_name='parentuser',
            name='UserChild3ID',
        ),
        migrations.RemoveField(
            model_name='parentuser',
            name='UserChild3Name',
        ),
    ]
